### ISSUE TITLE
Use native TextField and Native Button in Flash IDE and convert to starling native objects

### ISSUE THREAD

**Issue by BenoitFreslon** [tconkling/flump#140]
Hello,

Flump is a really good tool but I think that it will be awesome if we could use Flash native TextField and native buttons in Flash IDE and add custom parameters in the Symbols. 

I developed 2 years ago my own layout manager with Flash Components.

https://github.com/BenoitFreslon/benoitfreslon-layoutmanager

My lib converts the Components added in Flash IDE to Starling objects:
* Button
* TextField
* Sprite
* Image
* Quad

You also can set the instance name in Flash IDE and the instance variable is automatically set in your Starling class.

Unfortunately my lib can't export textures, motion tween. And you need to work with component placeholders in Flash IDE only.

<img src="https://raw.githubusercontent.com/BenoitFreslon/benoitfreslon-layoutmanager/master/demo/demo.jpg" />

**Comment by tconkling** [comment]
The reason this isn't a core Flump capability is because text handling varies so much from engine to engine, and text you create in Flash will likely not look the same in Flump. We want to keep the Flump core as basic as possible to keep it easy to port the Flump runtime to other engines/languages.

However, Flump is extensible - you can definitely develop on top of Flump to add custom capabilities like this!

**Comment by BenoitFreslon** [comment]
OK thanks!

Do you have the API Reference somewhere?

**Comment by tconkling** [comment]
Just the code itself, though I'm happy to provide pointers if you need help tracking something down!

**Comment by jackwlee01** [comment]
I think it could be worthwhile re-discussing this as a potential feature. I think at the very least runtime creators, or even library users, should somehow be able to attempt to make a reproduction of the text fields, even if there isn't complete consistency with how it appears in the Flash IDE. If the runtime itself does not display the text fields I think it should still provide the textfield data to the library users so that they can make choices as to how it is displayed.

In a given runtime, perhaps a delegate implementing in interface called ITextFieldCreator can be set in the Library which is called when a TextField is to be built. 

Alternatively, just having the textfield data available in the library.json would be immensely useful and give the library users the capacity to handle displaying text themselves for their own particular use-case.

**Comment by tconkling** [comment]
I've come around to this point of view and agree that exposing this sort of thing by default is the right way to go. I'm (still!) busy trying to ship my damn game, though :) - so I'm unlikely to take a look at this for a while at least.
