### ISSUE TITLE
Texture creation from flash.display.BitmapData

### ISSUE THREAD

**Issue by jkanchelov** [tconkling/flump#166]
Why texture creation is limited only from sprites ? I think it would be good if you could work with imported images too. 

Example: Having an flv you want in the fla . I am breaking it apart to sequence of images and when I import them in a movieclip symbol right now if I understand correctly I have to go trough all the images and make a symbol for them extending Sprite and after that it would work. 

Am I wrong and is there a better way to import and work with flv in the fla ? 

Thanks.

**Comment by tconkling** [comment]
Yes, this is a pain, and is unlikely to change without some serious work -- but it may be possible.

Flump uses the FLA to parse the symbol library and animation data; and it uses the SWF to create textures. This latter step it does by simply loading the SWF (the Flump exporter is a regular Flash app), instantiating Sprite symbols from the library, and rendering them to texture files.

"Bitmap" objects are not accessible to Flash runtime - it can only load named symbols, and Bitmaps aren't symbols. So there's no way to get them to work with this system. Support for Bitmaps would require an alternate texture-creation path; and would also require a different scheme for deciding which bitmaps are exported, since the "only export named Sprite symbols" scheme would of course not work here.

**Comment by mathieuanthoine** [comment]
@jkanchelov you don't need to convert each frame in a Sprite, you just have to make your MovieClip a Flipbook

See Flipbook documentation here : https://github.com/tconkling/flump#flipbook-creation

Hope it will help

**Comment by tconkling** [comment]
(Oh indeed, thanks for pointing that out @mathieuanthoine!)

**Comment by jkanchelov** [comment]
Thanks both of you guys @tconkling  @mathieuanthoine ! I will try it tomorrow . 

Till then I will leave this issue open if I have more questions about it later ( I hope I won't ..)
